**How to create a null values**
  - None
  - NP.NAN

In [1]:
import  numpy as np
import  pandas as pd

In [2]:
d={'Names':['Ramesh','Suresh',None,'SATHISH'],'Age':[None,22,24,25],'city':['hyd','blu','pune',None]}
df1=pd.DataFrame(d)
df1.to_csv('data1.csv',index=False)

In [4]:
d={'Names':['Ramesh','Suresh',np.nan,'SATHISH'],'Age':[np.nan,22,24,25],'city':['hyd','blu','pune',np.nan]}
df1=pd.DataFrame(d)
df1.to_csv('data2.csv',index=False)

- categorical data NOne

In [12]:
df1.isnull()

   Names    Age   city
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [14]:
df1.isnull().sum()

Names    1
Age      1
city     1
dtype: int64

In [17]:
df1.dtypes

Names     object
Age      float64
city      object
dtype: object

In [18]:
df1.isnull()

   Names    Age   city
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [19]:
df1.values

array([['Ramesh', nan, 'hyd'],
       ['Suresh', 22.0, 'blu'],
       [nan, 24.0, 'pune'],
       ['SATHISH', 25.0, nan]], dtype=object)

In [20]:
df1
df1.values
df1.dtypes
df1.isnull()
df1.isnull().sum()

Names    1
Age      1
city     1
dtype: int64

**fill the values**

In [22]:
df1.fillna(30)

     Names   Age  city
0   Ramesh  30.0   hyd
1   Suresh  22.0   blu
2       30  24.0  pune
3  SATHISH  25.0    30

In [25]:
#select one colun and will with value
df1['city'].fillna('delhi')

0      hyd
1      blu
2     pune
3    delhi
Name: city, dtype: object

In [26]:
df1

     Names   Age  city
0   Ramesh   NaN   hyd
1   Suresh  22.0   blu
2      NaN  24.0  pune
3  SATHISH  25.0   NaN

In [27]:
#pad,ffill,bfill,backfill
#asis=0 axis=1
df1.fillna(method='pad')

C:\Users\Dell\AppData\Local\Temp\ipykernel_5044\1870142242.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')

     Names   Age  city
0   Ramesh   NaN   hyd
1   Suresh  22.0   blu
2   Suresh  24.0  pune
3  SATHISH  25.0  pune

In [28]:
df1.fillna(method='pad',axis=1)

C:\Users\Dell\AppData\Local\Temp\ipykernel_5044\1258234312.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

     Names     Age  city
0   Ramesh  Ramesh   hyd
1   Suresh    22.0   blu
2      NaN    24.0  pune
3  SATHISH    25.0  25.0

In [29]:
df1.fillna(method='bfill')

C:\Users\Dell\AppData\Local\Temp\ipykernel_5044\2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

     Names   Age  city
0   Ramesh  22.0   hyd
1   Suresh  22.0   blu
2  SATHISH  24.0  pune
3  SATHISH  25.0   NaN

In [30]:
df1.fillna(method='bfill',axis=1)

C:\Users\Dell\AppData\Local\Temp\ipykernel_5044\2900121331.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill',axis=1)

     Names   Age  city
0   Ramesh   hyd   hyd
1   Suresh  22.0   blu
2     24.0  24.0  pune
3  SATHISH  25.0   NaN

- mean
- median
- mode

In [32]:
age_mean=df1['Age'].mean()
df1['Age'].fillna(age_mean)

0    23.666667
1    22.000000
2    24.000000
3    25.000000
Name: Age, dtype: float64

In [35]:
age_median=df1['Age'].median()
df1['Age'].fillna(age_median)

0    24.0
1    22.0
2    24.0
3    25.0
Name: Age, dtype: float64

In [ ]:
# there is no particular rule how to fille the mising values
# it is completely based on situation

In [37]:
Gender=['Males','Femail',None]
d1=pd.DataFrame(Gender,columns=['Genders'])

In [38]:
d1

  Genders
0   Males
1  Femail
2    None

In [40]:
d={'Female':0,'Males':1}
d1['Genders']=d1['Genders'].map(d)

In [41]:
d

{'Female': 0, 'Males': 1}

**sitution 2**

In [42]:
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0,5]

**sitution 3**

In [44]:
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

**situations-4**

In [ ]:
course=['DS','AI','DS','DEVOPS',

**KNNimputer**

- KNN : K-nearest neighbours
- where k is a number 
- instaed of taking avg of all  the values data
    - first will find neighbours who are closed with missing data
    - by using Euclidian distance  calculation  will idenify the neighbour rqwa
    - suppose k=2 will idenify the two closed  rows
    - those closest rows  values will take it,will calculation the mean
    - finally will fill with the mean

In [47]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),columns=['salary','Age'])

In [48]:
df

    salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- sklearn

    - impute

        - KNNimpute

In [50]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=20)
pd.DataFrame(imputer.fit_transform(df))

         0     1
0  50000.0  25.0
1  70000.0  28.0
2  70000.0  30.0
3  90000.0  40.0