In [ ]:
                                Data read
                                    |
                                Data cleaning
                                    |
                                Data Analysis
                                    |
                                Feature engineering
                                    |
                               Feature Selection
                                    |
                                Model development
                                    |
                                Model evaluation
                                    |
                                Model tuning
                                    |
                                Model deployment

**Feature Engineering**

- So far we have performed feature analysis

    - Data frame qucik checks

    - Categoroical column analsyis

    - Bar charts , pie charts

    - Numerical column analysis

    - Histograms, box plots , outliers

    - Bi-multi variate analysis 

    - correlation etc

- Now we need to learn Feature Engineering

    - we will create a new columns for better ML models

    - we will perform the **Encoding**,which is convert categorical to Numerical data

    - we will do data **transformations**

    - we will perform **Scaling: Standardization and Normalization**

    - we will perform the **missing value analayis**

- Simply feature engineering means our data will be modified

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv(r"C:\Users\Dell\Desktop\files\Visadataset.csv")
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

**case_status**

In [11]:
# first check how many unique lables are there in case_status
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [12]:
# create a dictinary 
d={'Certified':0,'Denied':1}

In [13]:
# map the above the dictionary with original column
visa_df['case_status']=visa_df['case_status'].map(d)

In [14]:
visa_df['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [15]:
labels=sorted(visa_df['education_of_employee'].unique())
d={j:i for i,j in enumerate(labels)}
visa_df['education_of_employee'].map(d)

0        2
1        3
2        0
3        0
4        3
        ..
25475    0
25476    2
25477    3
25478    3
25479    0
Name: education_of_employee, Length: 25480, dtype: int64

In [16]:
d

{"Bachelor's": 0, 'Doctorate': 1, 'High School': 2, "Master's": 3}

- there are two encodings

    - LabelEncoder

    - OrdinalEncoder

In [17]:
Ramesh  Suresh  Sathish: Nominal data
Red  Green Blue : Nominal data

SyntaxError: invalid syntax (2597070172.py, line 1)

In [18]:
Education     LabelEncoder   OrdinalEncoder
============================================
HighSchool       1            0

Bachelor         0            1

Masters          2            2

PH.D             3            3


1   0   2  3===> ML model sees this: 3>2>1>0
which indicates : PH.D>Matester>Hschool>Batchelors

SyntaxError: invalid syntax (1224815470.py, line 1)

In [19]:
# read the data again
visa_df=pd.read_csv(r'C:\Users\omkar\OneDrive\Documents\Gen_AI\Data_files\Visadataset.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\omkar\\OneDrive\\Documents\\Gen_AI\\Data_files\\Visadataset.csv'

In [20]:
- sklearn: **Package**

    - preprocessing: **module**

        - LabelEncoder: **class**

            - fit_transform:**method** 

import sklearn
skleran.preprocessing

from sklearn import preprocessing
dir(preprocessing): LabelEncoder
preprocessing.LabelEncoder

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform()

# Read the class
# save the class
# apply the fit transform

SyntaxError: invalid syntax (3065004978.py, line 1)

In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform

from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform

**fit transform**

- fit : created a dictionary(find something)

- transform: using above finding we are modify the data


from sklearn.module import class

va=class()

va.fit   or va.fit_transform

In [22]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

**LableEncoder**

In [24]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])

In [25]:
#read the data again
visa_df=pd.read_csv(r"C:\Users\Dell\Desktop\files\Visadataset.csv")

In [26]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    visa_df=le.fit_transform(visa_df[i])

In [27]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [29]:
from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder()
for i in cat[1:]:
    visa_df[i]=oe.fit_transform(visa_df[[i]])

In [30]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1.0,2.0,0.0,0.0,14513,2007,4.0,592.2029,0.0,1.0,1.0
1,EZYV02,1.0,3.0,1.0,0.0,2412,2002,2.0,83425.6500,3.0,1.0,0.0
2,EZYV03,1.0,0.0,0.0,1.0,44444,2008,4.0,122996.8600,3.0,1.0,1.0
3,EZYV04,1.0,0.0,0.0,0.0,98,1897,4.0,83434.0300,3.0,1.0,1.0
4,EZYV05,0.0,3.0,1.0,0.0,1082,2005,3.0,149907.3900,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1.0,0.0,1.0,1.0,2601,2008,3.0,77092.5700,3.0,1.0,0.0
25476,EZYV25477,1.0,2.0,1.0,0.0,3274,2006,2.0,279174.7900,3.0,1.0,0.0
25477,EZYV25478,1.0,3.0,1.0,0.0,1121,1910,3.0,146298.8500,3.0,0.0,0.0
25478,EZYV25479,1.0,3.0,1.0,1.0,1918,1887,4.0,86154.7700,3.0,1.0,0.0
25479,EZYV25480,1.0,0.0,1.0,0.0,3195,1960,1.0,70876.9100,3.0,1.0,0.0

In [31]:
visa_df=pd.read_csv(r"C:\Users\Dell\Desktop\files\Visadataset.csv")

- get dummies is a way to reprsent the categorical columns to numerical

- first it will  check what are the lables in a columns
- for example case status has to labels
     - Denied and certified
- so it will createtwo new columns based on labels
    - col1:case_status_Denied
    - col2: case_sttus_certified


case_status| case_status_Denied|case_status_certified
Denied     |          1       |          0
certified  |          0       |          1
certified  |          0       |          1

**it is also called as one hot encoder**
- it makes new columns are independent each other
- some of ml alorithms expect that columns sholud be independent each other

In [33]:
pd.get_dummies(visa_df['case_status'],dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]