In [2]:
import pandas as pd

In [3]:
pd.read_csv(r"C:\Users\Dell\Desktop\files\Visadataset.csv")

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

**step-1 Read the paxkages**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**step-2:Read the datasets**

In [2]:
visa_df=pd.read_csv(r"C:\Users\Dell\Desktop\files\Visadataset.csv")

In [3]:
bank_df=pd.read_csv(r"C:\Users\Dell\Desktop\files\bank.csv",sep=';')

In [4]:
bank_df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

**step-3:Data  Qucik Checks**

- shap
- size
- dtypes
- head
- tail
- columns
- isnull
- info

In [5]:
visa_df.shape

(25480, 12)

In [6]:
visa_df.size

305760

In [7]:
visa_df.head

<bound method NDFrame.head of          case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N
1         EZYV02      Asia              Master's                  Y
2         EZYV03      Asia            Bachelor's                  N
3         EZYV04      Asia            Bachelor's                  N
4         EZYV05    Africa              Master's                  Y
...          ...       ...                   ...                ...
25475  EZYV25476      Asia            Bachelor's                  Y
25476  EZYV25477      Asia           High School                  Y
25477  EZYV25478      Asia              Master's                  Y
25478  EZYV25479      Asia              Master's                  Y
25479  EZYV25480      Asia            Bachelor's                  Y

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007
1                         N             2412         2002
2                         Y            44444         2008
3                         N               98         1897
4                         N             1082         2005
...                     ...              ...          ...
25475                     Y             2601         2008
25476                     N             3274         2006
25477                     N             1121         1910
25478                     Y             1918         1887
25479                     N             3195         1960

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y
1                Northeast       83425.6500         Year                  Y
2                     West      122996.8600         Year                  Y
3                     West       83434.0300         Year                  Y
4                    South      149907.3900         Year                  Y
...                    ...              ...          ...                ...
25475                South       77092.5700         Year                  Y
25476            Northeast      279174.7900         Year                  Y
25477                South      146298.8500         Year                  N
25478                 West       86154.7700         Year                  Y
25479              Midwest       70876.9100         Year                  Y

      case_status
0          Denied
1       Certified
2          Denied
3          Denied
4       Certified
...           ...
25475   Certified
25476   Certified
25477   Certified
25478   Certified
25479   Certified

[25480 rows x 12 columns]>

In [8]:
visa_df.tail()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [9]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [10]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [11]:
visa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   case_id                25480 non-null  object
 1   continent              25480 non-null  object
 2   education_of_employee  25480 non-null  object
 3   has_job_experience     25480 non-null  object
 4   requires_job_training  25480 non-null  object
 5   no_of_employees        25480 non-null  int64
 6   yr_of_estab            25480 non-null  int64
 7   region_of_employment   25480 non-null  object
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object
 10  full_time_position     25480 non-null  object
 11  case_status            25480 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

In [12]:
type(visa_df)

pandas.core.frame.DataFrame

In [13]:
# what is the index of 'yr_of_estab'
cols=visa_df.columns
cols

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [14]:
cols.index('visa_df')

AttributeError: 'Index' object has no attribute 'index'

In [ ]:
cols=visa_df.columns.tolist()
cols.index('yr_of_estab')

In [ ]:
visa_df.head()

In [ ]:
# how you seeing as df in the  numpy language
#pandas === nimpy
# i df 25480 rows 12 cloumns
#numpy : bro i have   a array having  12  values

# these list are repeating 25480 times
np.array([1,2,3,4]) # i have a list 4 values 1 times

np.array([[1,2,3,4],[10,20,30,40]]).shape

In [19]:
# HOW you are seeing a df in the numpy language
visa_df #pandas
visa_df.values#numpy arrays

array([['EZYV01', 'Asia', 'High School', ..., 'Hour', 'Y', 'Denied'],
       ['EZYV02', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV03', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Denied'],
       ...,
       ['EZYV25478', 'Asia', "Master's", ..., 'Year', 'N', 'Certified'],
       ['EZYV25479', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV25480', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Certified']],
      shape=(25480, 12), dtype=object)

**loc-iloc**

In [ ]:
#visa_df.iloc[rows,columns]
#visa_df.iloc[start:stop:step:star:stop:step]
visa_df.iloc[2:6,3:7]

In [18]:
#loc will use ful we can provde  direct column names
#no need indexes
cols=['has_job_experience','requires_job_training']
visa_df.loc[2:6,cols]

  has_job_experience requires_job_training
2                  N                     Y
3                  N                     N
4                  Y                     N
5                  Y                     N
6                  N                     N

In [16]:
visa_df.iloc[[100,200],:3]
visa_df.iloc[[100,200],2:3:2]

    education_of_employee
100              Master's
200             Doctorate

In [ ]:
# every student sholud undersnd
# 1D and 2D
# list[] numpy: 1D pandas=series
#  list[[]] numpy: 2D pandas=DataFrame

In [15]:
visa_df['continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [ ]:
visa_df
visa_df['continent'] #1D s
visa_df[['continent']]#2D df
rows=[100,200,300]
visa_df.iloc[rows,3]#1d s
visa_df.iloc[rows,[3]]#2d d
visa_df.loc[rows,'continent'] # 1d
visa_df.loc[rows,['continent']]# 2d

In [ ]:
#1d is only one list :raw daa of a  specific colums
visa_df['continent'].values
2d is a list has 2 values: df 2 colums

**dtypes**
- every series is  a key valuepair
- every series is dictionary
- in dictionary if we want keys: .keys()
- in dictionary if we want values: .values

In [23]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [30]:
 keys=visa_df.dtypes.keys().tolist()

In [29]:
vales=visa_df.dtypes.values.tolist()

In [31]:
pd.DataFrame(zip(keys,vales),columns=['Names','Datatype'])

                    Names Datatype
0                 case_id   object
1               continent   object
2   education_of_employee   object
3      has_job_experience   object
4   requires_job_training   object
5         no_of_employees    int64
6             yr_of_estab    int64
7    region_of_employment   object
8         prevailing_wage  float64
9            unit_of_wage   object
10     full_time_position   object
11            case_status   object

In [34]:
df=pd.DataFrame(visa_df.dtypes).reset_index()
df.columns=['Names','DataType']
df

                    Names DataType
0                 case_id   object
1               continent   object
2   education_of_employee   object
3      has_job_experience   object
4   requires_job_training   object
5         no_of_employees    int64
6             yr_of_estab    int64
7    region_of_employment   object
8         prevailing_wage  float64
9            unit_of_wage   object
10     full_time_position   object
11            case_status   object

**tast-2**

In [ ]:
visa_df.dtypes
# idea 
# extract keys and values
# apply the for loop on values
# for i ,j in zip(values,keys):
#if i=='object'
#   j

In [41]:
keys=visa_df.dtypes.keys().tolist()

In [44]:
values=visa_df.dtypes.values.tolist()
cat,num=[],[]
for i ,j  in zip(keys,values):
    if i=='object':
        cat.append(i)
    else:
        num.append(j)
cat,num

([],
 [dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('int64'),
  dtype('int64'),
  dtype('O'),
  dtype('float64'),
  dtype('O'),
  dtype('O'),
  dtype('O')])

**select_dtypes**

In [47]:
visa_df.select_dtypes(include='object').columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [49]:
visa_df.select_dtypes(exclude='object').columns

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')