In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
Names=['Ramesh','Suresh','Sathish','Mahesh']
Age=[20,22,24,26]

**step-1:create a Dadaframe**

In [3]:
#pd.DataFrame(data,insex,columns,dtype,copy)
#pd.DataFrame(Names)
#pd.DataFrame(Names,'Names')
#pd.DataFrame(Names,columns='Names')
pd.DataFrame(Names,columns=['Names'])

     Names
0   Ramesh
1   Suresh
2  Sathish
3   Mahesh

In [4]:
pd.DataFrame(Names)
pd.DataFrame(Names,columns=['Names'])
pd.DataFrame(Names,index=['A','B','C','D'],columns=['Names'])

     Names
A   Ramesh
B   Suresh
C  Sathish
D   Mahesh

In [5]:
DATA=(Names,Age)
pd.DataFrame(DATA).T

         0   1
0   Ramesh  20
1   Suresh  22
2  Sathish  24
3   Mahesh  26

In [6]:
DATA=zip(Names,Age)
pd.DataFrame(DATA,columns=['Names','Age'])

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24
3   Mahesh   26

**step:-2 add a new column to already an existed df**

In [7]:
DATA=zip(Names,Age)
df=pd.DataFrame(DATA,columns=['Names','Age'])
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24
3   Mahesh   26

In [8]:
df[col_name ]#selection
        #updation
        #creationdf

NameError: name 'col_name' is not defined

In [ ]:
df['Names']

In [ ]:
df['Age']=[30,32,34,36]

In [ ]:
df

In [ ]:
df['city']=['hyd','pune','blr','Bihata']

In [ ]:
df

- created a datafreme with one column
- learned how to add a column names
- learn how to change the index
- create a dataframe with two coulmns using zip
- understand how to select update and create  new column with already existed dataframe

In [9]:
import pandas as pd
Names=['hi','hii','hiiii']
Age=[20,20,20]
pd.DataFrame(Names)

       0
0     hi
1    hii
2  hiiii

In [10]:
df=pd.DataFrame(Names,columns=["Name"])
df

    Name
0     hi
1    hii
2  hiiii

In [11]:
data=zip(Names,Age)
d=pd.DataFrame(data,columns=["Names","Age"])
d

   Names  Age
0     hi   20
1    hii   20
2  hiiii   20

In [12]:
d['city']=['hyd','blr','mum']

In [13]:
d

   Names  Age city
0     hi   20  hyd
1    hii   20  blr
2  hiiii   20  mum

In [14]:
d['Age']=['30','30','30']

In [15]:
d

   Names Age city
0     hi  30  hyd
1    hii  30  blr
2  hiiii  30  mum

**sept-3 How add add to data to empty dataframe**

In [16]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [17]:
df['names']=['Ramesh','Suresh','Sathish']
df['age']=[20,22,24]
df['city']=['hyd','blr','chennai']

df

     names  age     city
0   Ramesh   20      hyd
1   Suresh   22      blr
2  Sathish   24  chennai

**step-4 create a dataframe using dictionary**

In [15]:
d={'Names':['Ramesh','Suresh','Sathish'],'Age':[20,22,24],'city':['hyd','mum','null']}

d

{'Names': ['Ramesh', 'Suresh', 'Sathish'],
 'Age': [20, 22, 24],
 'city': ['hyd', 'mum', 'null']}

In [16]:
df=pd.DataFrame(d)
df

     Names  Age  city
0   Ramesh   20   hyd
1   Suresh   22   mum
2  Sathish   24  null

**step=5 drop a new column**

In [5]:
d={'Names':['Ramesh','Suresh','Sathish'],'Age':[20,22,24],'city':['hyd','mum','null']}
df

NameError: name 'df' is not defined

In [6]:
df.drop(Lables,axis=0,index,columns,inplace=True)

SyntaxError: positional argument follows keyword argument (2165944558.py, line 1)

In [ ]:
df.drop(lables,axis)
df.drop('city',axis=0)#index drop eror
df.drop('city',axis=1)#clumn drop

df.drop(coiumns=['city'])
df.frop(<argumets>)
dr.frop(a,b,c,d)
df.drop(2)
df.drop(z,axis=0)
df.drop('city')
df.drop('city',axis=1)

In [17]:
df.drop('city')

KeyError: "['city'] not found in axis"

In [18]:
df.drop('city',axis=1)

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [19]:
df.drop(2)

    Names  Age city
0  Ramesh   20  hyd
1  Suresh   22  mum

In [21]:
df.drop(2,axis=1)

KeyError: '[2] not found in axis'

In [30]:
df.drop('city',axis=1,inplace=True)
df

KeyError: "['city'] not found in axis"

In [24]:
df.drop(index=[2])df
#inplace=flase
#iplace=true=overwrite the output in same df

    Names  Age city
0  Ramesh   20  hyd
1  Suresh   22  mum

In [25]:
df

     Names  Age  city
0   Ramesh   20   hyd
1   Suresh   22   mum
2  Sathish   24  null

In [31]:
df.drop('city',axis=1,inplace=True)
df

KeyError: "['city'] not found in axis"

**ste-6 rename**

In [39]:
#df.rename(mapper)
#mapper  means dictionary
c={'Age':'citi'}
df.rename(c,axis=1)
df.rename(columns=c)

    Names  citi
0  Ramesh    20
1  Suresh    22

**step-7 save the  data frame**

In [ ]:
- .csv
- .xlsx
- where you  want to save :directory
- on whAT name you want save :names of the file
- on what extension you use :.csv,.xlsx
-diffrent location
- same loation:no need to provie dictectory :'dfls

In [41]:
df.to_csv(r"C:\Users\Dell\Desktop\files\df1.csv",index=False)

In [45]:
df.to_excel(r"C:\Users\Dell\Desktop\files\df2.xlsx",index=False)

**step-8 How to read a Dataframe**

In [48]:
pd.read_csv(r"C:\Users\Dell\Desktop\files\df1.csv")

    Names  Age
0  Ramesh   20
1  Suresh   22

In [51]:
pd.read_excel(r"C:\Users\Dell\Desktop\files\df2.xlsx")

    Names  Age
0  Ramesh   20
1  Suresh   22